resources:
  - name: concourse-examples
    type: git
    source:
      uri: https://github.com/ranjithgampa/concourse-examples.git
      branch: master
      username: ((github-username))
      password: ((github-password))
      
jobs:
- name: parameter-test
  serial_groups: [build-group-1]
  plan:
  - get: concourse-examples
  - task: inline-parameter-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ((LINUX_REPOSITORY))}
      run:
        path: env
        args: []
      params:
        CAT_NAME: ((github-username))
        DOG_NAME: ((github-password))  
        LINUX_REPOSITORY: ((LINUX_REPOSITORY))
- name: file-parameter-test
  serial_groups: [build-group-1]
  plan:
  - get: concourse-examples
  - task: file-parameter-test
    file: concourse-examples/tasks/parameter-test.yml
    params:
        CAT_NAME: ((github-username))
        DOG_NAME: ((github-password))    
        LINUX_REPOSITORY: busybox