platform: linux
image_resource:
  type: docker-image
  source: {repository: ((LINUX_REPOSITORY))}
run:
  path: env
  args: []
params:
  CAT_NAME: ((github-username))
  DOG_NAME: ((github-password))  
