platform: linux
image_resource:
  type: docker-image
  source: {repository: ((CAT_NAME))}
run:
  path: ls
  args: []
params:
  CAT_NAME: ((github-username))
  DOG_NAME: ((github-password)) 
  LINUX_REPOSITORY: ((LINUX_REPOSITORY))
